name 'ecs_test'
maintainer 'TANABE Ken-ichi'
maintainer_email 'nabeken@tknetworks.org'
license 'apache2'
description 'Installs/Configures ecs_test'
long_description 'Installs/Configures ecs_test'
version '0.1.0'
